language: python
python:
  - "2.7"
  - "2.6"
jdk:
  - oraclejdk6
before_install:
  - source ./scripts/ci/setup_env.sh
  - sudo apt-get update -qq
install: 
  - pip install protobuf 
  - pip install unittest2
  - pip install argparse
script: nosetests
env:
  - HADOOP_DISTRO=cdh
  - HADOOP_DISTRO=hdp
branches:
  except:
  - gh-pages
